Browse existing list
ELEVATE-Project/survey-project-creation-service pull request #146
Opened 2024-08-22 08:08 UTC by adithyadinesh0412

2024-08-22 13:23 UTC, priyanka-TL requested changes
Reviewed on Aug 22nd 6.53 PM

2024-08-22 13:23 UTC, priyanka-TL commented on src/controllers/v1/resource.js
> +				req.decodedToken.token.split(' ')[1],
@adithyadinesh0412  i think we can do this token conversion in interface

2024-08-22 13:23 UTC, priyanka-TL commented on src/generics/utils.js
> +const arrayPaginator = (data, page, size) => {
@adithyadinesh0412  rename this to paginate

2024-08-22 13:23 UTC, priyanka-TL commented on src/generics/utils.js
> +const arraySort = (data, sort) => {
@adithyadinesh0412  rename to sort

2024-08-22 13:23 UTC, priyanka-TL commented on src/generics/utils.js
> +const arraySort = (data, sort) => {
@adithyadinesh0412  add function signature

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +			const type = query[common.TYPE] ? query[common.TYPE] : ''
@adithyadinesh0412  please validate the type if they are passing

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +			const resources = await interfaceRequests.browseExistingList(type, organization_id, token, search)
@adithyadinesh0412  We should show the resources which is published only in scp. For example previously the  adopter is setting the CONSUMPTION_SERVICE as self. then that resources wont publish in the consumption side. But still they can use and copy that right ?

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +				const paginatedDated = utils.arrayPaginator(sortedData, pageNo, pageSize)
@adithyadinesh0412  change the names you dont need to explicitily tell that is array. just give paginateData or just paginate

2024-08-22 13:23 UTC, priyanka-TL commented on src/controllers/v1/resource.js
> +	 * @param {Object} req.query - Query object passed
@adithyadinesh0412 plesae add example for query

2024-08-22 13:23 UTC, priyanka-TL commented on src/generics/utils.js
> +const arraySort = (data, sort) => {
@adithyadinesh0412 add the signtaure and mention type array

2024-08-22 13:23 UTC, priyanka-TL commented on src/locales/en.json
> +	"BROWSE_EXISTING_LIST_FETCHING_FAILED": "Unable to the requested resource at the moment."
@adithyadinesh0412 the comma is missing after this line plesae add

2024-08-22 13:23 UTC, priyanka-TL commented on src/requests/interface.js
> +			let apiUrl = interfaceBaseUrl + endpoints.BROWSE_EXISTING_END_POINT
@adithyadinesh0412 can we use same browseExisting in interface

2024-08-22 13:23 UTC, priyanka-TL commented on src/controllers/v1/resource.js
> +	async browseExisting(req) {
@adithyadinesh0412 add this in validator and make sure if the type which frontend is passing valid

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +	 * @param {Object} query - Query object passed by user
@adithyadinesh0412 add sample data for query

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +	 * @param {string} organization_id - Org Id of the user
@adithyadinesh0412 change string to String

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +
@adithyadinesh0412 i think we need to check the status code also

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +				message: 'BROWSE_EXISTING_LIST_FETCHING_FAILED',
@adithyadinesh0412 we should send 200 with empty data

2024-08-22 13:23 UTC, priyanka-TL commented on src/services/resource.js
> +			const search = searchText != '' ? searchText : ''
@adithyadinesh0412 if the consumption service is self then we dont need to fetch the data from consumption side

2024-08-22 13:23 UTC, priyanka-TL commented on src/envVariables.js
> +		message: 'Browse Existing list end point',
@adithyadinesh0412 this is required only if the consumptionservice is not self

2024-08-23 04:17 UTC, priyanka-TL commented on src/services/resource.js
> +	static async browseExistingList(organization_id, token, query, searchText = '', pageNo, pageSize) {
@adithyadinesh0412 if observation with rubric u need to change the resource_type in response and also it is applicable to the searching , you don't have observation_with_rubric. Please handle the search and response changes

2024-08-23 09:50 UTC, adithyadinesh0412 commented on src/services/resource.js
> +			const type = query[common.TYPE] ? query[common.TYPE] : ''
type will be passed as a string with coma as delimiter. I don't think we can validate it here. We are not doing it any listing. @priyanka-TL

2024-08-23 10:50 UTC, priyanka-TL requested changes

2024-08-23 10:50 UTC, priyanka-TL commented on src/.env.sample
> +BROWSE_EXISTING_END_POINT=v1/internal/fetchResources
@adithyadinesh0412 as discussed add this only if the consumption service is not self

2024-08-23 10:50 UTC, priyanka-TL commented on src/envVariables.js
> +		message: 'Browse Existing list end point',
@adithyadinesh0412 make it optional add if consumption service is not self

2024-08-23 10:50 UTC, priyanka-TL commented on src/generics/utils.js
> +const arrayPaginator = (data, page, size) => {
@adithyadinesh0412 please change the function name

2024-08-23 10:50 UTC, priyanka-TL commented on src/generics/utils.js
> +const arraySort = (data, sort) => {
@adithyadinesh0412 please change the function name

2024-08-23 11:55 UTC, priyanka-TL commented on src/services/resource.js
> +			if (process.env.CONSUMPTION_SERVICE != common.SELF) {
@adithyadinesh0412  add comments

2024-08-23 11:57 UTC, priyanka-TL commented on src/services/resource.js
> +				resources?.success && resources?.data?.result?.data?.length > 0
@adithyadinesh0412  optimize this
let combinedData = [
  ...(resources?.success && resources?.data?.result?.data?.length ? resources.data.result.data : []),
  ...(selfResources.length ? selfResources : [])
];

2024-08-23 12:07 UTC, priyanka-TL commented on src/services/resource.js
> +				result: [],
@adithyadinesh0412  follow the same format data and count for empty result

2024-08-23 13:39 UTC, priyanka-TL approved these changes

2024-08-24 17:06 UTC, aks30 requested changes
Reviewed on 24 Aug

2024-08-24 17:06 UTC, aks30 commented on src/.env.sample
> +# mandatory only if CONSUMPTION_SERVICE is not self
@adithyadinesh0412 why do we need this in env? This can be hardcoded in scp service

2024-08-24 17:06 UTC, aks30 commented on src/controllers/v1/resource.js
> +	 * @name browseExisting
@adithyadinesh0412 we can call this resource/list

2024-08-25 12:27 UTC, adithyadinesh0412 commented on src/.env.sample
> +# mandatory only if CONSUMPTION_SERVICE is not self
This was added to for publishing the resources. Just reused the same here. @aks30

2024-08-25 12:49 UTC, adithyadinesh0412 commented on src/controllers/v1/resource.js
> +	 * @name browseExisting
Yes, Since this is a creator centric API we can add this with the `resource/list` API with `listing  = browse_existing `. @aks30

2024-08-26 12:53 UTC, adithyadinesh0412 commented
Merging this code to unblock QA. Further enhancement as per discussions will be done and pushed.

2024-08-26 12:54 UTC, merged