Entity types
ELEVATE-Project/survey-project-creation-service pull request #28
Opened 2024-05-15 11:40 UTC by adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu requested changes
Reviewed On 17 May 4:30

2024-05-17 10:57 UTC, ankit1shahu commented on src/.env.sample
>  AUTH_METHOD=jwt_only #or user_service_authenticated
Auth method we can say only 'jwt' no need to say jwt_only
@adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/controllers/v1/config.js
> +module.exports = class configs {
can you add some description for better understanding what it will do
@adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/models/organizationExtensions.js
> +			organization_id: {
it should be unique @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/models/organizationExtensions.js
> +			review_required: {
why the default value is false if show_reviewer_list is on that means you will be showing reviewer but by making false user can directly publish resources on the platform. If org admin wants to make any changes then he can update but by default we should keep it true.
@adithyadinesh0412 please confirm with @Prajwal17Tunerlabs as well

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/models/organizationExtensions.js
> +				type: DataTypes.STRING,
we can have enum value will be selected from sequential and parallel only please check that @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/queries/entityType.js
> +	static async findAllEntityTypes(orgIds, attributes, filter = {}) {
this function can not be called without org id and will return only org entity we can rename this function to findOrgEntityTypes @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/queries/entityType.js
> +	static async findAllEntityTypes(orgIds, attributes, filter = {}) {
we can pass the org id in the filter only why do we have to pass specifically @adithyadinesh0412 
Then this function can utilized other place as well

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/queries/entityType.js
> +			const entities = await Entity.findAll({
instead of importing entity model here we can create function in entity query file we can call from here @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/queries/entityType.js
> +			console.error('Error fetching data:', error)
we have logger we can use that for logging please don't use console log @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/database/queries/entityType.js
> +		try {
whats difference between above function findUserEntityTypesAndEntities and this function we can use only one function and we can pass different filters @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/envVariables.js
> +	REVIEW_REQUIRED: {
In model you have added default value false and here true it should be sync if user is not passing then @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/services/config.js
> +		let orgExtenstionData = {}
why variables are declared outside the try block @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/services/entity-types.js
> +		bodyData.created_by = id
why is this outside try block @adithyadinesh0412

2024-05-17 10:57 UTC, ankit1shahu commented on src/services/config.js
> +				organization_id,
@adithyadinesh0412 please optimize this function

2024-05-17 10:57 UTC, ankit1shahu commented on src/services/entity-types.js
> +		bodyData.updated_by = loggedInUserId
please declare all the variable in try block only @adithyadinesh0412

2024-05-20 14:22 UTC, adithyadinesh0412 commented on src/.env.sample
>  AUTH_METHOD=jwt_only #or user_service_authenticated
Its the same in mentoring, may be we can discuss this and take it up in a different PR

2024-05-20 14:30 UTC, adithyadinesh0412 commented on src/database/models/organizationExtensions.js
> +			organization_id: {
Removing this page as it's already added by priyanka

2024-05-20 14:48 UTC, adithyadinesh0412 commented on src/database/queries/entityType.js
> +	static async findAllEntityTypes(orgIds, attributes, filter = {}) {
So as you said in the previous comment, let the orgId be mandatory for this function and in the filter we can pass any additional filters we have. So to fetch the entity_types , org_id is a mandatory field.

2024-05-20 15:23 UTC, adithyadinesh0412 commented on src/database/queries/entityType.js
> +	static async findAllEntityTypes(orgIds, attributes, filter = {}) {
Removing this function as you said in the next comment. we can reuse findAllEntityTypesAndEntities()

2024-05-21 15:28 UTC, priyanka-TL commented on src/constants/endpoints.js
> +	ORGANIZATION_READ: 'v1/organization/read',
@adithyadinesh0412 this endpoint may vary in different user services, add this in the env

2024-05-21 15:28 UTC, priyanka-TL commented on src/controllers/v1/entity-types.js
> +module.exports = class Entity {
@adithyadinesh0412 change it to EntityType

2024-05-21 15:29 UTC, priyanka-TL commented on src/controllers/v1/entity-types.js
> +				req.params.id,
@adithyadinesh0412 params.id will have 1st priority

2024-05-22 09:15 UTC, adithyadinesh0412 commented on src/constants/endpoints.js
> +	ORGANIZATION_READ: 'v1/organization/read',
Sure

2024-05-24 08:59 UTC, priyanka-TL commented on src/.env.sample
> +ORGANIZATION_READ = 'v1/organization/read'
@adithyadinesh0412 change it to API_ENDPOINT_FOR_ORGANIZATION_READ

2024-05-24 09:17 UTC, priyanka-TL commented on src/services/entity-types.js
> +	static async create(bodyData, id, orgId) {
@adithyadinesh0412 change this id to loggedInUserId

2024-05-24 11:15 UTC, merged