form apis
ELEVATE-Project/survey-project-creation-service pull request #31
Opened 2024-05-21 16:09 UTC by priyanka-TL

2024-05-22 06:50 UTC, ankit1shahu requested changes
Reviewed On 22 May 12 PM

2024-05-22 06:50 UTC, ankit1shahu commented on src/services/form.js
> +			await KafkaProducer.clearInternalCache('formVersion')
kafka consumer and producer is not there please check this file from mentoring 
https://github.com/ELEVATE-Project/mentoring/blob/release-2.6.1/src/generics/kafka-communication.js
https://github.com/ELEVATE-Project/mentoring/blob/release-2.6.1/src/configs/kafka.js

@priyanka-TL @adithyadinesh0412

2024-05-22 06:50 UTC, ankit1shahu commented on src/services/form.js
> +			})
this function is also not present 
https://github.com/ELEVATE-Project/mentoring/blob/release-2.6.1/src/generics/form.js

@priyanka-TL

2024-05-24 10:03 UTC, adithyadinesh0412 commented
Approved on 24th May

2024-05-24 10:10 UTC, merged