Scp project create and update
ELEVATE-Project/survey-project-creation-service pull request #66
Opened 2024-06-24 04:18 UTC by ankit1shahu

2024-06-27 09:38 UTC, aks30 requested changes
Reviewed on 27 June

2024-06-27 09:38 UTC, aks30 commented on src/database/queries/entityModelMapping.js
> +exports.findModelAndEntityTypes = async (filter) => {
Rename this to findEntityTypes

2024-06-27 09:38 UTC, aks30 commented on src/services/entities.js
> +const entitiesQueries = require('@database/queries/entities')
Please rename it to entityQueries

2024-06-27 09:38 UTC, aks30 commented on src/services/entity-types.js
> +				if (bodyData.model) {
Where do we check if the model value is project only, and not any typo?

2024-06-27 09:38 UTC, aks30 commented on src/services/projects.js
> +				if (projectData.type !== common.PROJECT) {
Why do we have to check this if it's already happening in Line 186

2024-06-27 09:38 UTC, aks30 commented on src/services/projects.js
> +				if (projectData.title == '' || projectData.title == null) {
This can be in the validator no?

2024-06-27 09:38 UTC, aks30 commented on src/services/projects.js
> +				if (projectData.objective == '') {
This should be an entity type and validated as a generic code

2024-06-27 09:38 UTC, aks30 commented on src/services/projects.js
> +				for (let i = 0; i < entitiyTypes.length; i++) {
Where do we check single select or multi select?

2024-06-27 09:38 UTC, aks30 commented on src/services/projects.js
> +				if (projectData.tasks.length < 1) {
I think we should have entity types for project task and based on the validations we can put it here.

2024-07-02 13:00 UTC, priyanka-TL commented on src/constants/common.js
> +	RESOURCE_NOT_STARTED: 'NOT_STARTED',
@ankit1shahu change it to REVIEW_STATUS

2024-07-02 13:00 UTC, priyanka-TL commented on src/constants/common.js
> +	SUBMITTED: 'SUBMITTED',
@ankit1shahu already it is defined above use that RESOURCE_STATUS_SUBMITTED

2024-07-02 13:01 UTC, priyanka-TL commented on src/controllers/v1/projects.js
> +			const submitForReview = await projectService.submitForReview(req.decodedToken, req.params.id, req.body)
@ankit1shahu first params will be id then body then last token

2024-07-02 13:07 UTC, priyanka-TL commented on src/locales/en.json
> +	"SUB_TASK_NOT_FOUND": "Sub task not found",
@ankit1shahu Is this point addressed
The adopter should be able to set further validations for the links being added at the org level or instance level. For e.g. in DIKSHA only the diksha links should be allowed and thus the link added should be checked while saving for the same.

2024-07-02 13:09 UTC, priyanka-TL commented on src/locales/en.json
> +	"SUB_TASK_NOT_FOUND": "Sub task not found",
@ankit1shahu also 
See the text on top in the right section - "You can add combination of these resources: I- Learning Resource + Subtask; II- One observation; III- Only Learning Resource(s); IV- Only Subtasks"

subtask is not mandatory

2024-07-02 13:15 UTC, priyanka-TL commented on src/services/projects.js
> +const { Op, Utils } = require('sequelize')
@ankit1shahu is this Utils is using anywhere?

2024-07-02 13:22 UTC, priyanka-TL commented on src/services/projects.js
> +								message: 'SUB_TASK_NOT_FOUND',
@ankit1shahu SUb task is not mandatory

2024-07-02 13:23 UTC, priyanka-TL commented on src/services/projects.js
> +					{ id: projectData.id },
@ankit1shahu Are we validating only the project creator can update his project ? Add user id check also, Otherwise send error

2024-07-02 13:30 UTC, priyanka-TL commented on src/services/projects.js
> +						if (entityType.value !== 'tasks') {
@ankit1shahu add tasks in common

2024-07-02 13:31 UTC, priyanka-TL commented on src/services/projects.js
> +const specialCharRegex = /[^A-Za-z0-9 <>_&-]/
@ankit1shahu can we add this special character check in utils

2024-07-10 04:11 UTC, closed without merging